# Generated by Django 6.0.5 on 2026-05-30 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_posted_by_alter_job_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Score 0–100. Scores below 30 deduct rank points.')),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_rating', to='jobs.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
