# Generated by Django 6.0.5 on 2026-05-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_companyrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
