# Generated by Django 6.0.5 on 2026-05-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_application_interview_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='offer_response',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined')], help_text="Developer's response to a job offer", max_length=10),
        ),
    ]
