# Generated by Django 6.0.5 on 2026-05-31 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='application_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
