# Generated by Django 6.0.5 on 2026-05-30 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user.register', 'User Registered'), ('user.login', 'User Logged In'), ('user.logout', 'User Logged Out'), ('user.profile_update', 'Profile Updated'), ('user.tier_upgrade', 'Tier Upgraded'), ('job.view', 'Job Viewed'), ('application.create', 'Application Created'), ('application.update', 'Application Updated'), ('application.delete', 'Application Deleted'), ('saved_search.create', 'Saved Search Created'), ('saved_search.delete', 'Saved Search Deleted'), ('salary.submit', 'Salary Submitted')], db_index=True, max_length=50)),
                ('resource_type', models.CharField(blank=True, max_length=50)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
